# When CUPS support is enabled, support for running "chisel" as a CUPS
# filter is enabled, linking to the CUPS libraries and using extra features
# from them.
#
CHSL_CONFIG += CUPS

# Readline support will be used by the interactive REPL.
CHSL_CONFIG += READLINE

# Built with debugging aids
CHSL_CONFIG += DEBUG
