# Comment out the relevant lines to disable support for the
# corresponding Braille embossers
#
#CHSL_DEVICES += INDEXBRAILLE_V4
#CHSL_DEVICES += ONCE_PORTATHIEL
#CHSL_DEVICES += ONCE_BETA_X3
#CHSL_DEVICES += ONCE_BAX10
#CHSL_DEVICES += ONCE_IMPACTO

# When CUPS support is enabled, support for running "chisel" as a CUPS
# filter is enabled, linking to the CUPS libraries and using extra features
# from them.
#
CHSL_CONFIG += CUPS
CHSL_CONFIG += READLINE
CHSL_CONFIG += DEBUG
