--
-- texttochisel.lua
-- Copyright (C) 2012 Adrian Perez <aperez@igalia.com>
--
-- Distributed under terms of the MIT license.
--

-- header
print ("#!chisel")
print ("-- generated by texttochisel version " .. chisel.version)

-- FIXME This blindly copies the options from the command line.
--       There should be some validation here.
--
local optionformat = "    %s = [[%s]];"

print ("options {")
for key, value in pairs (chisel.options) do
	print (optionformat:format (key, value))
end
print ("}")

print ("document {")
print ("  text {")

for line in io.lines () do
	print (string.format ("    %q,", line .. "\n"))
end

-- footer
print ("  }")
print ("}")

