#! /usr/bin/env lua
--
-- texttochisel.lua
-- Copyright (C) 2012 Adrian Perez <aperez@igalia.com>
--
-- Distributed under terms of the MIT license.
--

-- header
print ("-- generated by texttochisel version " .. chisel.version)
print ("return document {")
print ("  text {")

for line in io.lines () do
	print (string.format ("    %q,", line .. "\n"))
end

-- footer
print ("  }")
print ("}")

